### ISSUE TITLE
Fix alignment in extension of yaml file

### ISSUE THREAD

**Issue by caredg** [HepUsfq2021/LEDAnalysis#6]
It seems like the [script](https://github.com/HepUsfq2021/LEDAnalysis/blob/master/LEDSkimmer/scripts/fileAppend.py) for extending the jobs in the yaml file is doing something weird with the identation:
https://github.com/HepUsfq2021/LEDAnalysis/blob/9edb8dfe0d52a518a12669459c710ee4ec4bc5cd/LEDSkimmer/scripts/fileAppend.py#L6

Please fix it as it will be needed to prepare the yaml file for k8s job submission

**Comment by littletalks134** [comment]
fixed
